### ISSUE TITLE
Can't connect to Alpha 1.2.3_04 server from Release 1.7.2-1.7.10.

### ISSUE THREAD

**Issue by AlphaTimes234** [RaphiMC/ViaProxy#21] opened 2023-02-23 12:50 UTC
Hi! When I try to log in to the alpha server 1.2.3_04, from version 1.7.2 to 1.7.10, after joining, my client crashes. Can you fix?

**Comment by AlphaTimes234** [comment] 2023-02-23 12:52
![изображение](https://user-images.githubusercontent.com/117481348/220911715-66b5a8db-1cea-4140-8a71-ec341e18dafa.png)

**Comment by RaphiMC** [comment] 2023-02-23 15:58
Can you please try to reproduce the error with the standalone ViaProxy program (Which this repository where you reported the issue is)

**Comment by AlphaTimes234** [comment] 2023-02-23 20:44
No error, Or I didn't understand what you were saying sorry
![изображение](https://user-images.githubusercontent.com/117481348/221025888-846979d5-f94a-4265-93f3-6cf7fb181d14.png)

**Comment by RaphiMC** [comment] 2023-02-23 20:45
Did it work tho? If yes this issue can be closed because the Bungeecord (ViaProxyConnect) is not really supported too well for 1.7 clients

**Comment by AlphaTimes234** [comment] 2023-02-23 21:25
No, i dont know how to activate standalone.

**Comment by RaphiMC** [comment] 2023-02-23 21:26
The standalone one runs on your computer and you join with the 1.7 client on the address it writes in the GUI. The readme should explain everything well

**Comment by AlphaTimes234** [comment] 2023-02-23 21:27
Oh i dumb, yes i will try.

**Comment by AlphaTimes234** [comment] 2023-02-23 21:29
Still crashing with GUI.

**Comment by RaphiMC** [comment] 2023-02-23 21:30
Can you send the error again. Just to make sure its the same error

**Comment by AlphaTimes234** [comment] 2023-02-23 21:31
![изображение](https://user-images.githubusercontent.com/117481348/221034817-0673aa11-be68-4311-bc64-f76c57ef8b7a.png)
![изображение](https://user-images.githubusercontent.com/117481348/221034837-b3c0a3fb-534f-4081-89d9-3df22b481822.png)
![изображение](https://user-images.githubusercontent.com/117481348/221034855-add6d231-3eb2-46b6-b0de-68f311260560.png)
![изображение](https://user-images.githubusercontent.com/117481348/221034872-c6ba
[crash-2023-02-23_23.29.43-client.txt](https://github.com/RaphiMC/ViaProxy/files/10818671/crash-2023-02-23_23.29.43-client.txt)
e9ff-f9a0-4413-874d-7d81802074e6.png)
[debug.log](https://github.com/RaphiMC/ViaProxy/files/10818672/debug.log)
[latest.log](https://github.com/RaphiMC/ViaProxy/files/10818673/latest.log)

All logs.

**Comment by AlphaTimes234** [comment] 2023-02-23 21:35
Previous Minecraft log:
[crash-2023-02-23_13.49.23-client.txt](https://github.com/RaphiMC/ViaProxy/files/10818688/crash-2023-02-23_13.49.23-client.txt)

**Comment by RaphiMC** [comment] 2023-02-24 13:20
Will be fixed when ViaProxy 3.0.14 releases

**Closed by RaphiMC** 2023-02-24 13:20 UTC
